apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-complik
  name: service-complik-config
  namespace: sealos
data:
  config.yml: |
    plugins:
      - name: "Complete"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "intervalMinute": 10080,
            "autoStart": false,
            "startTimeSecond": 30
          }

      - name: "Devbox"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "intervalMinute": 3000,
            "autoStart": true,
            "startTimeSecond": 30
          }

      - name: "Endpointslice"
        type: "Discovery"
        enabled: false
        settings: '{}'

      - name: "Deployment"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "resyncTimeSecond": 5,
            "ageThresholdSecond": 300
          }

      - name: "StatefulSet"
        type: "Discovery"
        enabled: true
        settings: |
          {
            "resyncTimeSecond": 5,
            "ageThresholdSecond": 300
          }

      - name: "Browser"
        type: "Compliance"
        enabled: true
        settings: |
          {
            "timeout": 100,
            "maxWorkers": 20
          }

      - name: "Safety"
        type: "Compliance"
        enabled: true
        settings: |
          {
            "maxWorkers": 20,
            "adminBaseURL": "http://sealos-complik-admin:8080",
            "adminTimeoutSecond": 10
          }

      - name: "Custom"
        type: "Compliance"
        enabled: false
        settings: |
          {
            "tickerMinute": 800,
            "maxWorkers": 20,
            "adminBaseURL": "http://sealos-complik-admin:8080",
            "adminTimeoutSecond": 10
          }

      - name: "AdminReporter"
        type: "Handle"
        enabled: true
        settings: |
          {
            "region": "hzh",
            "adminBaseURL": "http://sealos-complik-admin:8080",
            "adminTimeoutSecond": 10
          }

      - name: "Lark"
        type: "Handle"
        enabled: true
        settings: |
          {
            "region": "hzh",
            "adminBaseURL": "http://sealos-complik-admin:8080",
            "adminTimeoutSecond": 10
          }
    logging:
      level: "info"
    kubeconfig: "/kubeconfig/kubeconfig.yml"
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-complik
  name: service-complik-kubeconfig
  namespace: sealos
data:
  kubeconfig.yml: |
    apiVersion: v1
    kind: Config
    users:
      - name: read-only
        user:
          token:
    clusters:
      - cluster:
          certificate-authority-data: 
          server: 
        name: kubernetes
    contexts:
      - context:
          cluster: kubernetes
          user: read-only
        name: read-only-context
    current-context: read-only-context
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-complik
  name: service-complik-deployment
  namespace: sealos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-complik
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-complik
    spec:
      containers:
        - args:
            - --config=/config/config.yml
          command:
            - /manager
          image: bearslyricattack/sealos-complik-service:latest
          imagePullPolicy: Always
          name: service-complik
          ports:
            - containerPort: 8428
              protocol: TCP
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config-vol
            - mountPath: /kubeconfig
              name: kubeconfig-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: service-complik-config
          name: config-vol
        - configMap:
            defaultMode: 420
            name: service-complik-kubeconfig
          name: kubeconfig-vol
