plugins:
  - name: "Complete"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "intervalMinute": 10080,
        "autoStart": true,
        "startTimeSecond": 30
      }

  - name: "Devbox"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "intervalMinute": 3000,
        "autoStart": false,
        "startTimeSecond": 30
      }

  - name: "Endpointslice"
    type: "Discovery"
    enabled: false
    settings: '{}'

  - name: "Deployment"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "resyncTimeSecond": 5,
        "ageThresholdSecond": 300
      }

  - name: "StatefulSet"
    type: "Discovery"
    enabled: true
    settings: |
      {
        "resyncTimeSecond": 5,
        "ageThresholdSecond": 300
      }

  - name: "Browser"
    type: "Compliance"
    enabled: true
    settings: |
      {
        "timeout": 100,
        "maxWorkers": 20
      }

  - name: "Safety"
    type: "Compliance"
    enabled: true
    settings: |
      {
        "maxWorkers": 20,
        "adminBaseURL": "http://sealos-complik-admin:8080",
        "adminTimeoutSecond": 10
      }

  - name: "Custom"
    type: "Compliance"
    enabled: true
    settings: |
      {
        "tickerMinute": 800,
        "maxWorkers": 20,
        "adminBaseURL": "http://sealos-complik-admin:8080",
        "adminTimeoutSecond": 10
      }

  - name: "AdminReporter"
    type: "Handle"
    enabled: true
    settings: |
      {
        "region": "${REGION}",
        "adminBaseURL": "http://sealos-complik-admin:8080",
        "adminTimeoutSecond": 10
      }

  - name: "Lark"
    type: "Handle"
    enabled: true
    settings: |
      {
        "region": "${REGION}",
        "adminBaseURL": "http://sealos-complik-admin:8080",
        "adminTimeoutSecond": 10
      }

logging:
  level: "info"

kubeconfig: "${KUBECONFIG_PATH}"
