apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "procscan.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "procscan.labels" . | nindent 4 }}
data:
  config.yaml: |
    scanner:
      proc_path: {{ .Values.config.scanner.proc_path | quote }}
      scan_interval: {{ .Values.config.scanner.scan_interval | quote }}
      log_level: {{ .Values.config.scanner.log_level | quote }}

    actions:
      annotation:
        enabled: {{ .Values.config.actions.annotation.enabled }}
      forceDelete:
        enabled: {{ .Values.config.actions.forceDelete.enabled }}

    notifications:
      admin:
        base_url: {{ .Values.config.notifications.admin.base_url | quote }}
        timeout: {{ .Values.config.notifications.admin.timeout | quote }}
