apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: block-controller
  labels:
    app.kubernetes.io/name: block-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: block-controller
subjects:
  - kind: ServiceAccount
    name: block-controller
    namespace: block-system
