name: Build Image

on:
  workflow_call:
    inputs:
      context:
        description: Docker build context.
        required: true
        type: string
      image:
        description: Container image repository.
        required: true
        type: string
      artifact-name-prefix:
        description: Prefix for the digest artifact name.
        required: true
        type: string
      arch:
        description: Target CPU architecture.
        required: true
        type: string
      runs-on:
        description: GitHub Actions runner label.
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.image }} (${{ inputs.arch }})
    permissions:
      contents: read
      packages: write
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ inputs.image }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ${{ inputs.context }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/${{ inputs.arch }}
          outputs: type=image,"name=${{ inputs.image }}",name-canonical=true,push-by-digest=${{ github.event_name != 'pull_request' }},push=${{ github.event_name != 'pull_request' }}

      - name: Export digest
        run: |
          mkdir -p "${{ runner.temp }}/digests"
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: ${{ inputs.artifact-name-prefix }}-${{ inputs.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1
